### ISSUE TITLE
Error (0xffffffffffffffff) with use mod jewerly

### ISSUE THREAD

**Issue by neVoid12** [ZsoltMolnarrr/Jewelry#10]
I use multimc and when using the jewelry mod, I get an error (I found it out by selection)
error: The process is completed with the code -1 (0xffffffffffffffff).
Please note that usually neither the exit code nor its description is sufficient to diagnose problems!
Always download the entire log, not just the exit code.

How can I fix this? I have the latest version of java, the multimc settings are fine, there are no computer failures and I have the latest version of the launcher

**Comment by ZsoltMolnarrr** [comment]
This report does not contain enough information to provide any help.
Please join our discord server, and follow the troubleshooting guide.
