### ISSUE TITLE
Jewelry sometime disappear 

### ISSUE THREAD

**Issue by 13E0** [ZsoltMolnarrr/Jewelry#11]
I'm running this via Sinytra Connector with Forge,
Also running a server too, with 200+ modpack.
And I notice sometimes when I log back in game, the trinket slot clear the item I have,
Some case I manage to reduce the bug I found:
+ When enter another dimension the necklace slot replace to another one, and the Ring is gone.
This not happen often, so could I get a clarification from the dev team ?

**Comment by ZsoltMolnarrr** [comment]
Hello!
I'm afraid this might be a sinytra specific issue.
Do other trinket items disappear from other mods? For example Supplementaries (Fabric) Quiver
