### ISSUE TITLE
Retroactive ore generation

### ISSUE THREAD

**Issue by ShibeTemple** [ZsoltMolnarrr/Jewelry#13]
Would it be possible to retroactively generate the gem ores in a pre-made or already explored world?

**Comment by ZsoltMolnarrr** [comment]
Nope sorry, that is not how the game works. :(

**Comment by von-get** [comment]
Not a great solution, but I _think_ the Chunky trim command can be used to delete some chunks from your world, effectively 'unexploring' it.  Then when you visit them again, I think they could generate again. Not a big deal if you have a house and don't care about anything outside of that, but if you've built in multiple areas and want to keep that then basically no.
