### ISSUE TITLE
Suggestion: Allow configuration of how common gem veins are.

### ISSUE THREAD

**Issue by von-get** [ZsoltMolnarrr/Jewelry#18]
Although I'm sure some would appreciate very in-depth abilities to tweak gem spawns, personally, a simple multiplier would suffice.

Personally, I would use it to set the spawn rate to 0, so that jewelry is only found as rare loot in dungeons, but I'm sure others would appreciate the ability to raise or lower the quantity that is spawned in the world.

**Comment by ZsoltMolnarrr** [comment]
Gem spawns are not possible to adjust using mod configs.

Instead regular datapacks can do this.
