### ISSUE TITLE
Jewelry attribute changes not saving.

### ISSUE THREAD

**Issue by RoertDoer** [ZsoltMolnarrr/Jewelry#24]
Using version 1.3.7 for 1.20.1. I am using this mod through Sinytra Connector on a Forge server. The mod works fine with no errors. However, no config changes will appear in game. This is a shared issue with your other RPG Series mods. Just looking to eliminate user error before looking at compatibility issues.

Can you verify I have no syntax errors in this config change?:

`` "jewelry:unique_archer_necklace": {
      "attributes": [
        {
          "id": "ranged_weapon:damage",
          "value": 0.25,
          "operation": "MULTIPLY_BASE"
        }``

**Comment by ZsoltMolnarrr** [comment]
I think the config changes does actually work on the server side, it just doesn't appear to have an effect when clients look at particular items.

For this reason, config file, as part of pre-made modpack distributable are recommended to bundled together.
