### ISSUE TITLE
Request: Use Curios instead of Trinkets when running on Forge using Sinytra Connector

### ISSUE THREAD

**Issue by TyrionReyukra** [ZsoltMolnarrr/Jewelry#4]
I am a forge user working on my own modpack, and have been experimenting with Sinytra Connector to see what fabric mods I can run on forge with little to no issue. After seeing that the "RPG" mod series says it works with forge thanks to Sinytra Connector, I decided to do some testing.

From my experience with the RPG mods series, I have had no game breaking issues.
The only thing I've found is the request stated in the title of this post.

Curios is the main accessory system on forge and it would be nice to have the accessories adapt depending on which accessory system in installed.

Things can get pretty messy having both Trinkets and Curios installed, leading to multiple of slots of the same type across two different menu systems. I've tried to do what I can using tag editing with datapacks to remove the Jewelry accessories from Trinkets slots and into Curios slots. But doing so rendered the Jewelry items useless, removing any sort of stat bonuses the item would normally provide.

Allowing them be equipped in both types of accessory systems lets them keep their stats in their descriptions, but they only apply in the trinkets slots.

I'm not sure how high of a priority forge compatibility is since this seems to be primarily a fabric mod, but Sinytra Connector seems very promising and I would like to do what I can to see the two platforms work together as seamlessly as possible.

**Comment by TyrionReyukra** [comment]
My apologies, I just read through the comments on curseforge and saw that the curios issue will not be fixed.
Hopefully these split-loader issues will be fixed some point in the future with NeoForge or something similar.
I understand being a solo dev is tough, and I wish you the best of luck with your projects.

**Comment by HatelessHeart** [comment]
> I am a forge user working on my own modpack, and have been experimenting with Sinytra Connector to see what fabric mods I can run on forge with little to no issue. After seeing that the "RPG" mod series says it works with forge thanks to Sinytra Connector, I decided to do some testing.
> 
> From my experience with the RPG mods series, I have had no game breaking issues. The only thing I've found is the request stated in the title of this post.
> 
> Curios is the main accessory system on forge and it would be nice to have the accessories adapt depending on which accessory system in installed.
> 
> Things can get pretty messy having both Trinkets and Curios installed, leading to multiple of slots of the same type across two different menu systems. I've tried to do what I can using tag editing with datapacks to remove the Jewelry accessories from Trinkets slots and into Curios slots. But doing so rendered the Jewelry items useless, removing any sort of stat bonuses the item would normally provide.
> 
> Allowing them be equipped in both types of accessory systems lets them keep their stats in their descriptions, but they only apply in the trinkets slots.
> 
> I'm not sure how high of a priority forge compatibility is since this seems to be primarily a fabric mod, but Sinytra Connector seems very promising and I would like to do what I can to see the two platforms work together as seamlessly as possible.

Hey man, Im a modpack creator and an amateur developer as well as a photoshop texture artist. Can we connect via discord? My discord ID is "HatelessHeart" and my discord is working on a project with soome similarities. Here is my personal discord where we are working a modpack project called "Skyland Adventures" also thinking about renaming the project to "Escape from the Skylands:  https://discord.gg/XWRZAEpVTt
