### ISSUE TITLE
Jewelry stats failing to be applied.

### ISSUE THREAD

**Issue by SelkeGore** [ZsoltMolnarrr/Jewelry#6]
Item's such as the Sentinel's Amulet & Juggernaut Band are failing to give armor nor health.

**Comment by ZsoltMolnarrr** [comment]
They do.
Screenshot from Dungeon Heroes modpack.
(Wearing Sentinel's Amulet and Iron Ring)
![Screenshot 2024-02-05 at 22 57 36](https://github.com/ZsoltMolnarrr/Jewelry/assets/4989469/713537f1-bba3-472c-86f6-b3c922e66d71)

I recommend checking for incompatible mods or Trinkets data configuration.
